title: <p align="center"> David Desquens </p>
  
logo: "/images/personal_rounded_enhanced.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/desquens/">LinkedIn</a> | 
  <a href="https://github.com/ddesquens">GitHub</a> | 
  <a href="https://www.kaggle.com/anonymousds">Kaggle</a>
  </p>

  <p align="justify">
  I am a Senior Data Analyst with an education background of double degree in Industrial & Management Engineering at Universitat Politècnica de Catalunya (ETSEIB) & Politecnico di Milano respectively.
  <br><br>
  Welcome to my data science and analytics portfolio where I show some of my personal projects involving the usage of R, Python and Machine Learning among others.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
